/* Gaussian elimination code.
 * 
 * Author: Naga Kandasamy
 * Date created: February 7
 * Date of last update: April 10, 2019
 *
 * Compile as follows: gcc -o gauss_eliminate gauss_eliminate.c compute_gold.c -O3 -Wall -std=c99 -lpthread -lm
 */

#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <sys/time.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include "gauss_eliminate.h"

#define MIN_NUMBER 2
#define MAX_NUMBER 50

typedef struct thread_data_s
{
	int tid;
	Matrix A;
	Matrix u_mt;
	unsigned int i, j, k;
	unsigned int num_elements;
	int num_threads;
	
} thread_data_t;


/* Function prototypes. */
extern int compute_gold (float *, unsigned int);
Matrix allocate_matrix (int, int, int);
void gauss_eliminate_using_pthreads (Matrix, int);
int perform_simple_check (const Matrix);
void print_matrix (const Matrix);
float get_random_number (int, int);
int check_results (float *, float *, unsigned int, float);


int
main (int argc, char **argv)
{
    /* Check command line arguments. */
    if (argc > 1) {
        printf ("Error. This program accepts no arguments.\n");
        exit (EXIT_FAILURE);
    }

    Matrix A;			    /* Input matrix. */
    Matrix U_reference;		/* Upper triangular matrix computed by reference code. */
    Matrix U_mt;			/* Upper triangular matrix computed by pthreads. */

    /* Initialize the random number generator with a seed value. */
    srand (time (NULL));

    A = allocate_matrix (MATRIX_SIZE, MATRIX_SIZE, 1);	            /* Allocate and populate a random square matrix. */
    U_reference = allocate_matrix (MATRIX_SIZE, MATRIX_SIZE, 0);	/* Allocate space for the reference result. */
    U_mt = allocate_matrix (MATRIX_SIZE, MATRIX_SIZE, 0);	        /* Allocate space for the multi-threaded result. */

    /* Copy the contents of the A matrix into the U matrices. */
    for (int i = 0; i < A.num_rows; i++) {
        for (int j = 0; j < A.num_rows; j++) {
            U_reference.elements[A.num_rows * i + j] = A.elements[A.num_rows * i + j];
            U_mt.elements[A.num_rows * i + j] = A.elements[A.num_rows * i + j];
        }
    }

    printf ("Performing gaussian elimination using the reference code.\n");
    struct timeval start, stop;
    gettimeofday (&start, NULL);
    
    int status = compute_gold (U_reference.elements, A.num_rows);
  
    gettimeofday (&stop, NULL);
    printf ("CPU run time = %0.2f s.\n", (float) (stop.tv_sec - start.tv_sec +\
                (stop.tv_usec - start.tv_usec) / (float) 1000000));

    if (status == 0) {
        printf ("Failed to convert given matrix to upper triangular. Try again. Exiting.\n");
        exit (EXIT_FAILURE);
    }
  
    status = perform_simple_check (U_reference);	/* Check that the principal diagonal elements are 1. */ 
    if (status == 0) {
        printf ("The upper triangular matrix is incorrect. Exiting.\n");
        exit (EXIT_FAILURE);
    }
    printf ("Single-threaded Gaussian elimination was successful.\n");
  
    /* Perform the Gaussian elimination using pthreads. The resulting upper 
     * triangular matrix should be returned in U_mt */
    gauss_eliminate_using_pthreads (U_mt,4);

    /* check if the pthread result matches the reference solution within a specified tolerance. */
    int size = MATRIX_SIZE * MATRIX_SIZE;
    int res = check_results (U_reference.elements, U_mt.elements, size, 0.0001f);
    printf ("TEST %s\n", (1 == res) ? "PASSED" : "FAILED");

    /* Free memory allocated for the matrices. */
    free (A.elements);
    free (U_reference.elements);
    free (U_mt.elements);

    exit (EXIT_SUCCESS);
}


/* FIXME: Write code to perform gaussian elimination using pthreads. */
void
gauss_eliminate_using_pthreads (Matrix U, int num_threads)
{
	int i;
	
	pthread_t* thread_id = (pthread_t *) malloc(sizeof(pthread_t) * num_threads); //This allocates the memory needed for the total amount of threads
	thread_data_t *thread_data_array = (thread_data_t *) malloc(sizeof(thread_data_t) * num_threads);
	pthread_attr_t attributes; //
	pthread_attr_init (&attributes);
	printf("Chuck size = %i\n", chunk_size);
	for(i = 0; i < num_threads; i++)
	{
		thread_data_array[i].
		thread_data_array[i].num_elements = chuck_size;

		if(i == num_threads - 1)
		{
			thread_data_array[i].num_elements = n - chuck_size * (num_threads - 1);
			// Print feedback here
		}
		
		thread_data_array[i].tid = i;
		thread_data_array[i].num_threads = num_threads;
		//Print some more feedback?
	}
	for (i = 0; i < num_threads; i++)
	{
		pthread_join (thread_id[i], NULL);
	}
	free((void *) thread_data_array);
}


/* Function checks if the results generated by the single threaded and multi threaded versions match. */
int
check_results (float *A, float *B, unsigned int size, float tolerance)
{
    for (int i = 0; i < size; i++)
        if (fabsf (A[i] - B[i]) > tolerance)
            return 0;
    return 1;
}


/* Allocate a matrix of dimensions height*width
 * If init == 0, initialize to all zeroes.  
 * If init == 1, perform random initialization. 
*/
Matrix
allocate_matrix (int num_rows, int num_columns, int init)
{
    Matrix M;
    M.num_columns = M.pitch = num_columns;
    M.num_rows = num_rows;
    int size = M.num_rows * M.num_columns;
    M.elements = (float *) malloc (size * sizeof (float));
  
    for (unsigned int i = 0; i < size; i++) {
        if (init == 0)
            M.elements[i] = 0;
        else
            M.elements[i] = get_random_number (MIN_NUMBER, MAX_NUMBER);
    }
  
    return M;
}


/* Returns a random floating-point number between the specified min and max values. */ 
float
get_random_number (int min, int max)
{
    return (float)
        floor ((double)
                (min + (max - min + 1) * ((float) rand () / (float) RAND_MAX)));
}

/* Performs a simple check on the upper triangular matrix. Checks to see if the principal diagonal elements are 1. */
int
perform_simple_check (const Matrix M)
{
    for (unsigned int i = 0; i < M.num_rows; i++)
        if ((fabs (M.elements[M.num_rows * i + i] - 1.0)) > 0.0001)
            return 0;
  
    return 1;
}
